"""series metadata fields

Revision ID: 24ead41f23c1
Revises: 209e21bbb483
Create Date: 2026-06-05 22:53:51.668658

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ead41f23c1'
down_revision: str | None = '209e21bbb483'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('metadata_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('metadata_provider')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
