"""series format duration end_year

Revision ID: 7199a3585194
Revises: 9101f7dcb25d
Create Date: 2026-06-06 00:34:58.211600

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7199a3585194'
down_revision: str | None = '9101f7dcb25d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('episode_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('end_year')
        batch_op.drop_column('episode_duration')
        batch_op.drop_column('format')

    # ### end Alembic commands ###
