"""series display and native title

Revision ID: 9101f7dcb25d
Revises: c6081e5efce7
Create Date: 2026-06-06 00:27:57.763421

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9101f7dcb25d'
down_revision: str | None = 'c6081e5efce7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Plain ADD COLUMN (not batch) so it applies in-place without an exclusive
    # table rebuild — safe to run while the dev server holds the SQLite file.
    op.add_column('series', sa.Column('display_title', sa.String(), nullable=True))
    op.add_column('series', sa.Column('native_title', sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('native_title')
        batch_op.drop_column('display_title')

    # ### end Alembic commands ###
