"""series synopsis, score, genres, banner

Revision ID: d40a1ea5dde3
Revises: 24ead41f23c1
Create Date: 2026-06-05 23:38:26.418417

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40a1ea5dde3'
down_revision: str | None = '24ead41f23c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('genres')
        batch_op.drop_column('score')
        batch_op.drop_column('description')
        batch_op.drop_column('banner_image_url')

    # ### end Alembic commands ###
